### ISSUE TITLE
Magenta showing wrong color

### ISSUE THREAD

**Issue by ExcitedName** [Turkey2349/Colored-Name-Tags#1]
![2018-03-24_20 45 17](https://user-images.githubusercontent.com/17900146/37871511-4da3fae2-2fa4-11e8-8dff-01947d7af5a6.png)

**Comment by TheTurkeyDev** [comment]
Hmmmmmm. Seems that would be a vanilla issue then since I'm simply pulling the chat text colors from the dyes them selves. I will look into it though

**Comment by ExcitedName** [comment]
That's what I figured based on the colors I saw. They look just like when you change text color via commands. Thanks for your time and energy.

**Comment by TheTurkeyDev** [comment]
No problem! Interesting that that is a bug with vanilla mc.
